name: deploy_firebase_hosting

on:
  push:
    branches:
      - master
      
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        run: yarn deploy --token=${{ env.FIREBASE_DEPLOY_KEY }}
