name: deploy_firebase_hosting

on:
  push:
    branches:
      - main
      
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: install firebase-tool
        run: yarn add --dev firebase-tools
      - name: Deploy to Firebase
        run: ./node_modules/.bin/firebase deploy --token=${{ secrets.FIREBASE_DEPLOY_KEY }}
